{
  <#if request.username??>"username": "${request.username}"</#if>
  <#if request.firstname??>,"firstname": "${request.firstname}"</#if>
  <#if request.lastname??>,"lastname": "${request.lastname}"</#if>
  <#if request.emailaddress??>,"emailaddress": "${request.emailaddress}"</#if>
  <#if request.personnelnumber??>,"personnelnumber": "${request.personnelnumber}"</#if>
  <#if request.positiondescription??>,"positiondescription": "${request.positiondescription}"</#if>
  <#if request.userobjectdescr??>,"userobjectdescr": "${request.userobjectdescr}"</#if>
  <#if request.talentsegmentdescr??>,"talentsegmentdescr": "${request.talentsegmentdescr}"</#if>
  <#if request.employeesubgroupdescr??>,"employeesubgroupdescr": "${request.employeesubgroupdescr}"</#if>
  <#if request.homeoffice??>,"homeoffice": "${request.homeoffice}"</#if>
  <#if request.countryname??>,"countryname": "${request.countryname}"</#if>
  <#if request.gu??>,"gu": "${request.gu}"</#if>
  <#if request.domainspecialty??>,"domainspecialty": "${request.domainspecialty}"</#if>
  <#if request.workforcegroup??>,"workforcegroup": "${request.workforcegroup}"</#if>
  <#if request.capabilitydescr??>,"capabilitydescr": "${request.capabilitydescr}"</#if>
  <#if request.orglevel1desc??>,"orglevel1desc": "${request.orglevel1desc}"</#if>
  <#if request.orglevel2desc??>,"orglevel2desc": "${request.orglevel2desc}"</#if>
  <#if request.orglevel3desc??>,"orglevel3desc": "${request.orglevel3desc}"</#if>
  <#if request.serviceline??>,"serviceline": "${request.serviceline}"</#if>
  <#if request.orglevel5desc??>,"orglevel5desc": "${request.orglevel5desc}"</#if>
  <#if request.orglevel6desc??>,"orglevel6desc": "${request.orglevel6desc}"</#if>
  <#if request.industryspecialtydescr??>,"industryspecialtydescr": "${request.industryspecialtydescr}"</#if>
  <#if request.careertrackdesc??>,"careertrackdesc": "${request.careertrackdesc}"</#if>
  <#if request.orglevel4desc??>,"orglevel4desc": "${request.orglevel4desc}"</#if>
  <#if request.supervisornm??>,"supervisornm": "${request.supervisornm}"</#if>
  <#if request.industrycapabilitydescr??>,"industrycapabilitydescr": "${request.industrycapabilitydescr}"</#if>
  <#if request.professionalbio??>,"professionalbio": "${request.professionalbio}"</#if>
  <#if request.thumbnailurl??>,"thumbnailurl": "${request.thumbnailurl}"</#if>
  <#if request.imgurl??>,"imgurl": "${request.imgurl}"</#if>
  <#if request.peoplekey??>,"peoplekey": "${request.peoplekey}"</#if>
  <#if request.homecity??>,"homecity": "${request.homecity}"</#if>
  <#if request.standardjobdescr??>,"standardjobdescr": "${request.standardjobdescr}"</#if>
  <#if request.companycd??>,"companycd": "${request.companycd}"</#if>
}